#!/bin/sh

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

message="$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_ROLE in $KAMAL_RUNTIME seconds $KAMAl_ROLE"
data='{"text":"'"$message"'"}'
curl -X POST -H 'Content-type: application/json' --data $data $SLACK_WEBHOOK_URL
