# Name of your application. Used to uniquely configure containers.
service: deals-hub-be

# Name of the container image.
image: dthtien/deal-hub-backend

# Deploy to these servers.
servers:
  web:
    hosts:
      - 67.219.97.246
    labels:
      traefik.http.routers.kiqr_cloud.rule: Host(`api.beneficiumvilis.com`)
      traefik.http.routers.kiqr_cloud_secure.entrypoints: websecure
      traefik.http.routers.kiqr_cloud_secure.rule: Host(`api.beneficiumvilis.com`)
      traefik.http.routers.kiqr_cloud_secure.tls: true
      traefik.http.routers.kiqr_cloud_secure.tls.certresolver: letsencrypt
    options:
      network: "private"
  job:
    hosts:
      - 67.219.97.246
    cmd: bundle exec sidekiq -C config/sidekiq.yml
    options:
      network: "private"


# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: dthtien

  # Always use an access token rather than real password when possible.
  password:
    - REGISTRY_PASSWORD

accessories:
  redis:
    image: redis:latest
    roles:
      - web
      - job
    directories:
      - redis:/data
    options:
      network: "private"

  postgres:
    image: postgres:15
    host: 67.219.97.246
    port: 5432:5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_USER
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: "private"

env:
  clear:
    REDIS_URL: redis://deals-hub-be-redis:6379
    APP_URL: https://www.beneficiumvilis.com/
    DEAL_HUB_API_DATABASE_HOST: deals-hub-be-postgres
  secret:
    - RAILS_MASTER_KEY
    - DEAL_HUB_API_DATABASE_NAME
    - DEAL_HUB_API_DATABASE_USERNAME
    - DEAL_HUB_API_DATABASE_PASSWORD
    - SLACK_WEBHOOK_URL
    - FB_PAGE_ID
    - FB_USER_TOKEN

# Use a different ssh user than root
ssh:
  user: deploy


# Configure custom arguments for Traefik. Be sure to reboot traefik when you modify it.
traefik:
  options:
    network: "private"
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "tiendt2311@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
