:concurrency: 5
production:
  :concurrency: 10
pidfile: tmp/pids/sidekiq_development.pid
:queues:
  - critical
  - default
  - low
:scheduler:
  :schedule:
    craw_all:
      cron: "0 6,12,18 * * *"
      class: "Crawlers::DistributeJob"
    post_bargain:
      cron: "0 19 * * *"
      class: "PostBargainJob"


