name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - name: Preparing database
        run: bundle exec rails db:setup db:migrate

      - name: Run tests
        run: bundle exec rspec

  push_to_registry:
    needs: test
    name: Push Docker image to Azure
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: dthtien.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        run: |
          docker build . -t dthtien.azurecr.io/${{ github.repository }}:${{ github.sha }}
          docker push dthtien.azurecr.io/${{ github.repository }}:${{ github.sha }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Cluster Authentication
        run: echo "$KUBECONFIG" > /tmp/kubeconfig
        env:
          KUBECONFIG:  ${{secrets.KUBECONFIG}}

      - name: Deploying
        run: |
          kubectl --kubeconfig=/tmp/kubeconfig rollout restart deployment deals-hub-be-deployment

